export type Colors =
  | 'primary'
  | 'secondary'
  | 'info'
  | 'success'
  | 'warning'
  | 'danger'
  | 'light'
  | 'dark'
export type Sizes = 'sm' | 'md' | 'lg' | 'xl'
export type Variants = 'contained' | 'outlined' | 'text'
