name: release
on:
  push:
    branches:
      - dev
jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: chmod u+x script.sh
      - run: git config --global user.email "foggdev@gmail.com"
      - run: git config --global user.name "Versioning Bot"
      - run: npm run versioning
